services:
  master:
    build:
      context: ./master
    container_name: ipxe-master
    network_mode: host
    volumes:
      - ./boot:/var/www/boot:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
